"""users, invite_codes, exit_applications

Revision ID: 655d312f26f0
Revises: 
Create Date: 2026-08-07 15:07:26.866681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '655d312f26f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('student', 'teacher', 'guard', 'admin', name='user_role'),
               existing_nullable=False,
               postgresql_using="role::user_role")
        batch_op.alter_column('surname',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=60),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=60),
               existing_nullable=False)
        batch_op.alter_column('lastname',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=60),
               existing_nullable=True)
        batch_op.alter_column('group_number',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=True)
        batch_op.alter_column('campus',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('pole', 'mozaika', name='campus_type'),
               existing_nullable=True,
               postgresql_using="campus::campus_type")
        batch_op.alter_column('login',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=64),
               existing_nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=128),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('users_login_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_users_fio', ['surname', 'name', 'lastname'], unique=False)
        batch_op.create_index('ix_users_group', ['group_number', 'group_letter'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_group_letter'), ['group_letter'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_group_number'), ['group_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_login'), ['login'], unique=True)
        batch_op.drop_column('is_dostup')
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('is_dostup', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_index(batch_op.f('ix_users_login'))
        batch_op.drop_index(batch_op.f('ix_users_group_number'))
        batch_op.drop_index(batch_op.f('ix_users_group_letter'))
        batch_op.drop_index('ix_users_group')
        batch_op.drop_index('ix_users_fio')
        batch_op.drop_index(batch_op.f('ix_users_created_at'))
        batch_op.create_unique_constraint(batch_op.f('users_login_key'), ['login'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('login',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('campus',
               existing_type=sa.Enum('pole', 'mozaika', name='campus_type'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('group_number',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('lastname',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('surname',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('role',
               existing_type=sa.Enum('student', 'teacher', 'guard', 'admin', name='user_role'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
